packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'web'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

overrides:
  vite: $vite

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
